### ISSUE TITLE
[CLI] "libman cache clean <provider>" command results in funky file paths in error message when file is locked

### ISSUE THREAD

**Issue by alexgav** [aspnet/LibraryManager#131]
### Functional impact
*No functional impact, but we should clean up file paths if we can*  

### Minimal repro steps

1. Install some libraries, e.g. cdnjs jquery@3.2.1
2. Go to the cache location for the library, e.g. C:\Users\alexgav\.librarymanager\cdnjs\jquery\3.2.1
3. Open one of the files, e.g. jquery.js
4. Execute

```
libman cache clean cdnjs
```

### Expected result
Error message specifying which file is locked

### Actual result
Error message Failed to clean cache: The process cannot access the file '\\?\C:\Users\alexgav\.librarymanager\cdnjs\jquery\3.2.1' because it is being used by another process.

### Further technical details
*Not sure why the file path is in the "windows internals" format, \\?\c:\xxx*, instead of "c:\xxx", hopefully we can normalize

**Comment by jimmylewis** [comment]
I don't think we can do much here.  We try to delete the directory, and that's locked because of the open handle on the file.  We don't know which file it is, and looking up open handles on a given file (e.g. if we iterated all the files) is non-trivial on Windows (it needs custom drivers, UAC, security, oh my!), and not applicable on other OS (since they typically don't hold locks on files).

As for the path format, that's coming from the inner exception, possibly a .NET Core behavior.  I don't think it's worth messing with that either (doesn't seem worth the effort).
