### ISSUE TITLE
[Add Library Dialog] It would be nice to have a keyboard shortcut for the dialog. 

### ISSUE THREAD

**Issue by alexgav** [aspnet/LibraryManager#225]
### Functional impact
*It's a bit painful to go through right-click on a folder, then click on Add, then wait for another menu, and finally click Add Client Library menu item*  

### Minimal repro steps

1. Try invoking Add Library Dialog a few times. 

### Expected result
*Should be quick and easy*  

### Actual result
*It takes several clicks and waiting for the menus to open*  

### Further technical details
*While the users can add keyboard shortcut themselves, not everybody will know how to do it, and then they need to choose Project.Add.ClientSideLibrary command* Might be a pain to find  a decent unused shortcut.

**Comment by justcla** [comment]
Good suggestion. However, it's very hard to find free/available keyboard shortcuts in Visual Studio. Where it's really important to have a shortcut (ie. editor command) and/or we expect very high usage, then we have to go through the pain of selecting a new VS shortcut. Where we can avoid it, we do, so that it frees up more keyboard mapping space for extension authors and user preferences.

However, I feel the pain of using LibMan with a keyboard. Many actions are only available on a context menu on specific items in the Solution Explorer, which is annoying to find and access - and somewhat unnecessary given that many commands are project-global and don't really need any folder context.

As such, I propose we solve the keyboard accessibility issue by adding menu items to the main "Project" menu. They would each have accelerator keys, so you could activate any LibMan command with a few keystrokes no matter where your focus is at the time.
This would mean:
- no need to navigate to Solution Explorer
- no need to locate libman.json
- no need to open right-click context menu

Would that be a better solution?
(Rather than introducing new VS shortcuts that could only be used in web projects.)

**Comment by justcla** [comment]
I have raised issue #196 to address this.

**Comment by jimmylewis** [comment]
Closing this in favor of #196.
