### ISSUE TITLE
.NET CLI support

### ISSUE THREAD

**Issue by madskristensen** [aspnet/LibraryManager#3]
It should be possible to run the various commands from the CLI

**Comment by guardrex** [comment]
As we were just chatting about over in https://github.com/dotnet/templating/issues/1263, templates have been a problem for documentation samples and explaining ASP.NET Core technology to non-Windows/non-VS devs. Many of the doc samples were derived from templates. Authors (including myself) haven't worked hard enough to shore them up for a broader audience, especially for example, the use of Bower and `BundlerMinifier.Core`.

I don't even know sitting here today what happens if targets and the tool reference is present and VS extension(s) are present that light-up Bower and `BundlerMinifier.Core`. Idk if it goes :boom: or runs those features twice or just works. I do know that without the project file entries, non-VS devs are out-of-luck getting those features to work without the project file enhancements. 

I hope when you get to the subject of template modifications for `LibraryInstaller` that whatever CLI commands and whatever tooling `DotNetCliToolReference`s are required that they're included in the template OOB (or easy to light-up with a `dotnet new <template>` command-line switch).
