### ISSUE TITLE
Can not install at VS 15.7.5

### ISSUE THREAD

**Issue by lettucebo** [aspnet/LibraryManager#302]
### Functional impact
Can not install at VS 15.7.5.

### Minimal repro steps

At the VS 15.7.5 install using self build vsix fail
I also try download and install the vsix from AppVeyor artifacts's vsix

All get: Install Error : System.InvalidOperationException: A value for 'Component' needs to be specified in the catalog.

### Further technical details
Here is the log file: 
[VSIXInstaller_54ee3b27-6c08-4a09-b289-977623dfbe8a.log](https://github.com/aspnet/LibraryManager/files/2186936/VSIXInstaller_54ee3b27-6c08-4a09-b289-977623dfbe8a.log)

**Comment by JLOrdaz** [comment]
I hace same problem with same version of Visual Studio

**Comment by jodavis** [comment]
This is happening because we changed `IsProductComponent` to `true` here:
https://github.com/aspnet/LibraryManager/blob/72bf21f2c5fc56447e27f0ed1b866154d0fb520c/src/LibraryManager.Vsix/Microsoft.Web.LibraryManager.Vsix.csproj#L30
When it was `false`, Library Manager could be installed on versions of Visual Studio that didn't already have Library Manager (15.7 or lower). However, it would fail to update if Visual Studio already had Library Manager (15.8 Preview or higher).

We changed it to `true` so the latest builds could be used to update 15.8 Previews. The trade-off is that those builds no longer install on older versions of Visual Studio.

You can work around this in your own builds by changing that value back to `false`. That's only necessary until you can upgrade to 15.8. Then you'll need to change it back to `true`.
