### ISSUE TITLE
Install Library dialog does not handle scoped package names (starting with '@') well

### ISSUE THREAD

**Issue by kellcomnet2** [aspnet/LibraryManager#352]
### Functional impact
I am unable to add a client side library for fontawesome due to an error.

### Minimal repro steps
Open Add Client-Side Library
Select "unpkg" as the provider
Search for "@fortawesome/fontawesome-free"
Select the package
No files appear in the list and if you choose install it fails with the "@fortawesome/fontawesome-free" library could not be resolved by the unpkg provider

### Expected result
You would be able to add the package

### Actual result
No files appear in the list and if you choose install it fails with the "@fortawesome/fontawesome-free" library could not be resolved by the unpkg provider

### Additional Details
If you manually type a second @ it will give you the version list and you can choose a specific version and it works. It appears to be an issue caused by the @ in the package path/name

**Comment by nickalbrecht** [comment]
This might be related to #329

**Comment by kellcomnet2** [comment]
Yes it does appear to be related, I didn't notice the significance of the @ until after I posted the issue originally. I then amended the details.

**Comment by biehlermi** [comment]
Is there a workaround available for this bug?

**Comment by Altafard** [comment]
I was be able to find the package by full name and version '@fortawesome/fontawesome-free@5.5.0' but seems that it cannot be installed. What's problem?

**Comment by Altafard** [comment]
There is some update - it's all ok for me

![default](https://user-images.githubusercontent.com/28362919/47967251-86f39400-e06c-11e8-84a1-316583adb035.png)

**Comment by ASKemp** [comment]
Not working for me

**Comment by robinwilson16** [comment]
It looks like this is fixed now.
I have had to comment Font Awesome out from my libman.json files for to get it to compile for the last two weeks but today the package resolves correctly and everything was downloaded to the correct folder.

This is what I use:
```
{
  "provider": "unpkg",
  "library": "@fortawesome/fontawesome-free@5.6.3",
  "destination": "wwwroot/lib/font-awesome/"
},
```
Maybe someone else can confirm?

**Comment by jimmylewis** [comment]
I think this is separate from #329 because the repro steps for this issue are when there is only a single @ sign.  I can still repro with the original steps, and it seems like the error returned should better indicate that the version is missing from the library ID.

**Comment by robinwilson16** [comment]
Since my post on 6th Jan this has been an intermittent problem but more recently it has consistently failed every time.
My projects stall on build so I need to stop and comment out the reference to fontawesome in libman.

Errors are that files failed to download:
`
Error	LIB010	Failed to download resource from "http://unpkg.com/@fortawesome/fontawesome-free@5.6.3/svgs/regular/arrow-alt-circle-right.svg"	ProjectName	...\libman.json	20	
`
Is there a more reliable repository that we should be using instead given this has been an issue for about 6 months now since last August?

**Comment by kellcomnet2** [comment]
I have removed fontawesome from libman and am manually including the files - sucks that i have to add them to SCM but since it is so unreliable no choice.

**Comment by jimmylewis** [comment]
I've noticed that all of the providers we support have been pretty flaky on initial downloads - lots of 404s, etc.  Anecdotally, Unpkg has been the worst for me, but YMMV.

In #440 I added a retry loop when downloading files and this has made my reliability go up significantly.  This change will be shipping in VS2019 Preview 4.

**Comment by clintnetwork** [comment]
https://github.com/unpkg/unpkg.com/issues/178

**Comment by robinwilson16** [comment]
Yes there did seem to be a while when CDNJS was having random issues too although I think that one is ok for me at the moment.
The retry should improve things otherwise the build process just hangs for ages and it is not clear what is stopping it.

**Comment by bzhu94** [comment]
Fixed with [PR 499](https://github.com/aspnet/LibraryManager/pull/499) and [PR 504](https://github.com/aspnet/LibraryManager/pull/504).

There still is the issue where the latest version isn't filled when a package is selected in the dropdown for name completion for Unpkg and JsDelivr, but I have a PR [here](https://github.com/aspnet/LibraryManager/pull/507) to address that.

Also, there is the issue of showing a more actionable and clearer error message when a library version isn't specified and the user tries to hit the "install" button, which I've logged a new issue for [here](https://github.com/aspnet/LibraryManager/issues/508)
