### ISSUE TITLE
command not found: libman on macOs

### ISSUE THREAD

**Issue by seanmars** [aspnet/LibraryManager#367]
### Functional impact
command not found: libman

### Minimal repro steps
1. install libman via `dotnet tool install -g Microsoft.Web.LibraryManager.Cli`
2. `libman --version`

### Expected result
Current version of libman

### Actual result
dotnet tool install -g Microsoft.Web.LibraryManager.Cli

### Further technical details

**Comment by justcla** [comment]
Did the tool install properly?
Was there output on the command line indicating success? Or was there an error?

Are you able to uninstall the CLI, then try to install it and capture the logs?

**Comment by seanmars** [comment]
> Did the tool install properly?
> Was there output on the command line indicating success? Or was there an error?
> 
> Are you able to uninstall the CLI, then try to install it and capture the logs?

Ok, I'll try to get more information.

**Comment by seanmars** [comment]
@justcla here the the log of `dotnet tool install -v d -g Microsoft.Web.LibraryManager.Cli`

https://gist.github.com/seanmars/4507d486d8c94f992c47c484f5ae72a8

**Comment by trancynn** [comment]
I'm also having issues with invoking libman. Logs are pretty much the same as the ones @seanmars posted.

**Comment by jimmylewis** [comment]
@trancynn just to confirm, it sounds like the issue you're seeing isn't specific to libman then?  This workaround fixes both libman and dotnet-aspnet-codegenerator?

**Comment by seanmars** [comment]
I've figured out that I can make the `~/.dotnet/tools/libman` to `~/.dotnet/tools/dotnet-libman`, then I can use `dotnet libman`, but the document just actually use `libman`. [how to use libman](https://docs.microsoft.com/en-us/aspnet/core/client-side/libman/libman-cli?view=aspnetcore-2.1#usage)

I guess the `libman` not same as other dotnet tools, but it installed by `dotnet tool install`, maybe it's need put `libman` under the `/usr/bin`, not `~/.dotnet/tools`

**Comment by trancynn** [comment]
@jimmylewis Thanks for your quick response! 
I agree, this issue might not be specific to libman, but I would still love to see if we can make the installation smoother.

**Comment by qnoturas** [comment]
Had the same issue and just created a link in my path like so:

`sudo ln -s ~/.dotnet/tools/libman /usr/local/bin/libman`

Hope it helps..

**Comment by Brucius** [comment]
@qnoturas this worked!! thanks

**Comment by seanmars** [comment]
This tool still not work on macOS. It's needs make the link manually. Is there any new news about this issue?

**Comment by Wuriqilang** [comment]
> This tool still not work on macOS. It's needs make the link manually. Is there any new news about this issue?
qnoturas's measure is right

**Comment by simonech** [comment]
I've the same problem, macOS Catalina 10.15. NET Core 3.0
My PATH contains the `~/.dotnet/tools` folder
```
PATH=/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/share/dotnet:~/.dotnet/tools:/Library/Frameworks/Mono.framework/Versions/Current/Commands
```
But simply calling `libman` gives me the same error: `zsh: command not found: libman`

Renaming the folder from `libman` to `dotnet-libman` (and then calling `dotnet libman`) solved the problem.

**Comment by jimmylewis** [comment]
Let me preface this by observing that the issues here all seems to be zsh related.  If anyone is hitting this issue on a different shell (like bash), please reply and I can investigate further.

The install experience for dotnet tools by default does not work well with zsh (as documented [here](https://github.com/dotnet/cli/issues/9321)).  When installing the libman tool (or any other), you need to pay attention to the output (emphasis added):

>~ % dotnet tool install --global Microsoft.Web.LibraryManager.CLI
>Tools directory '/Users/jimmy/.dotnet/tools' is not currently on the PATH environment variable.
>**If you are using zsh, you can add it to your profile by running the following command:
>cat << \EOF >> ~/.zprofile
>\# Add .NET Core SDK tools
>export PATH="$PATH:/Users/jimmy/.dotnet/tools"
>EOF
>And run `zsh -l` to make it available for current session.**
>You can only add it to the current session by running the following command:
>export PATH="$PATH:/Users/jimmy/.dotnet/tools"
>You can invoke the tool using the following command: libman
>Tool 'microsoft.web.librarymanager.cli' (version '2.0.96') was successfully installed.

When I followed these steps, invoking `libman` worked fine.

Using @qnoturas's suggestion works by creating a symlink in a directory that's already included in the $PATH.  It basically accomplishes the same but in a way that would be generic across shells (and requires sudo permissions).

Renaming libman to dotnet-libman like @seanmars suggests works because then it's the `dotnet` executable trying to locate the tool rather than the shell.  `dotnet` knows to look in the correct folder regardless of whether it's been added to $PATH.

There isn't really anything we could do as part of the libman package to address this experience (unless we were to change it to always be invoked as dotnet-libman, which I don't think we're considering at this time).

**Comment by simonech** [comment]
@jimmylewis the problem is that with Catalina, the default shell is zsh... so all dotnet tools will have issues.
I agree, not an issue with libman specifically, but to be addressed at dotnet CLI level.

**Comment by jimmylewis** [comment]
I definitely agree that with zsh as the default in Catalina, this is a poor experience.  IMO it would be an improvement for the warning message to come after the successful installation (because if the last thing in the output is "<tool> installed successfully" I'm probably not going to read the rest), and in a warning color.  But that's for the CLI team to decide...

@simonech I forgot to mention in your specific case: zsh does not expand `~` the same as bash when used in $PATH, so you need to use `/Users/<name>/.dotnet/tools` on Mac (see [this comment](https://github.com/dotnet/cli/issues/9321#issuecomment-390725508))

**Comment by Nikhil3180** [comment]
You have to run the following command to install libman on your mac os

**_dotnet tool install -g Microsoft.Web.LibraryManager.Cli_**

After running the above command try

**_libman --version_**

If you get the error Command not found: libman

Then also run the following command

_**export PATH="$PATH:/Users/username/.dotnet/tools"**_

where username would be your macOS user

**Comment by AveryKing** [comment]
> `sudo ln -s ~/.dotnet/tools/libman /usr/local/bin/libman`

ty <3
