### ISSUE TITLE
Migration from other VS tooling to libman

### ISSUE THREAD

**Issue by ghost** [aspnet/LibraryManager#371]
I've got a project that was created before libman, it's pretty much got the standard bootstrap/jquery files in the web project. There doesn't seem to be a way to migrate these easily to libman - would it be possible to have a feature to upgrade or migrate from whatever Visual Studio was using before to libman?

**Comment by justcla** [comment]
That would be very tricky. Libraries change too frequently and the list of files differ between providers.
Migrating the bootstrap and jquery libraries will need to be done manually.

However, the bootstrap/jquery scenario is so common that we might be able to publish the library config for fetching the equivalent files from the default templates.

**Comment by jimmylewis** [comment]
I think the best way for this to resolve is to get the default templates to have a libman.json file for their assets.  There isn't really a sustainable way that we can recognize assets in the project and produce a libman.json file for those files, for a number of reasons (not least of which is #407, since the templates don't follow the same file layouts as the libraries we can get from our provider catalogs).

I'm resolving this issue, but @jodavis I wonder if we should chat with the template folks on this topic again.  I know there used to be some interest in leveraging libman for these assets, as they're currently pretty much unmanaged.
