### ISSUE TITLE
Files not populating in Intellisense (unpkg), library not resolved on build

### ISSUE THREAD

**Issue by catriname** [aspnet/LibraryManager#383]
### Functional impact
restoration of packages fails, build fails

### Minimal repro steps
1. specify provider: unpkg
2. library: bulma-checkradio (appears on intellisense for me, no versions)
3. specify destination
4. files does not populate in intellisense

### Expected result
right click restore packages, they populate into destination specified

### Actual result
The "bulma-checkradio" library could not be resolved by the "unpkg" provider
Restore operation completed with errors

### Further technical details
VS Pro 15.8.7

{"provider": "unpkg", "library": "bulma-checkradio", "destination": "wwwroot/lib/bulma", "files": [] },

also did not work for: datatables-bulma

i was able to bring them in via packages.json and then transfer them from _node_modules to my wwwroot/lib destination using libman filesystem provider, but not directly with unpkg

**Comment by alexgav** [comment]
This is due to the fact that unpkg provider requires library version to be specified, but it doesn't make it obvious. We filed #394 to address that. 

Meanwhile, if you type "@" after the library name, you should get intellisense for library versions (or you can just type one in yourself). With the version specified, everything should work properly. 

Since we already have #394, I'll go ahead and close this issue. If you are still having problems, please re-activate. We will work to improve experience in the unpkg provider.
