### ISSUE TITLE
How to use behind proxy that require authentication?

### ISSUE THREAD

**Issue by DavoBR** [aspnet/LibraryManager#399]
### Minimal repro steps
Run the following command in console

`libman install bootstrap -d wwwroot/lib/bootstrap --files dist/css/bootstrap.css --files dist/css/bootstrap.min.css --files dist/js/bootstrap.js --files dist/js/bootstrap.min.js`

### Expected result
Download the library files

### Actual result
Microsoft.Web.LibraryManager.Contracts.ResourceDownloadException: Failed to download resource from "http://unpkg.com/bootstrap/package.json"
   at Microsoft.Web.LibraryManager.WebRequestHandler.GetStreamAsync(String url, CancellationToken cancellationToken)
   at Microsoft.Web.LibraryManager.Extensions.GetJsonObjectViaGetAsync(IWebRequestHandler webRequestHandler, String url, CancellationToken cancellationToken)   at Microsoft.Web.LibraryManager.Providers.Unpkg.UnpkgCatalog.GetLatestVersion(String libraryName, Boolean includePreReleases, CancellationToken cancellationToken)
The "bootstrap" library could not be resolved by the "unpkg" provider

### Further technical details

- I am behind corporate proxy that require  authentication
- The solution that I am currently using is activating traffic capture in Fiddler while I am using libman

**Comment by jmcmillen** [comment]
I'm having the same problem behind a corporate proxy that requires authentication.  I was just on my way over to submit an issue when I saw this one already created.  

`libman restore` produces the same error as @DavoBR submitted.

> libman.json : error LIB002: The "bootstrap@4.1.3" library could not be resolved by the "unpkg" provider

`dotnet build` causes the same error when Enable Restore Client-Side Libraries on Build is selected.

I'd like to add that running `msbuild` directly on the project works.  I thought dotnet.exe was built on top of msbuild so I'm not sure why dotnet.exe isn't working too.

**Comment by speedcodenet** [comment]
I have the same issue. We need a way to specify a proxy server.

**Comment by wshuman3** [comment]
We are experiencing this issue with a azure devops/vsts build agent behind a proxy.  

I tried to switch to msbuild as @jmcmillen  suggested and that isn't working either.

**Comment by Roman-Tarasiuk** [comment]
I have similar problem behind corporate proxy:
when I run **libman install jquery**
I get error: [LIB002] library could not be resolved by the "cdnjs"

**Comment by hpsanampudi** [comment]
I do have same problem when I am trying to publish ASP.Net core web application to azure container registry.
_libman.json : error LIB002: The "jquery@3.3.1" library could not be resolved by the "cdnjs" provider
libman.json : error LIB002: The "jquery-validate@1.18.0" library could not be resolved by the "cdnjs" provider
..._

**Comment by TRM79-Temp** [comment]
@madskristensen, @raquelsa, @bhsubra, @prafullbhosale, @alexgav, @jimmylewis – any suggestions?

**Comment by jimmylewis** [comment]
Anyone running into this - can you let me know what responses you're getting, e.g. through Fiddler?  Are you getting HTTP 407 responses from the proxy?

I don't have a proxy here so I'm approaching this from what I can find with my googlebing-fu.

**Comment by Roman-Tarasiuk** [comment]
@jimmylewis,
In the command window I run command:
libman install bootstrap
and get message (Russian Windows):
Не удалось скачать каталог от поставщика "cdnjs"
[LIB002]: Поставщику "cdnjs" не удалось разрешить библиотеку "bootstrap"
(Cannot download catalogue from the provider "cdnjs"
[LIB002]: library "bootstrap" could not be resolved by the provider "cdnjs")
In the Fiddler the libman tries to connect:
CONNECT aka.ms:443 HTTP/1.1
and gets response:
HTTP/1.1 407 authenticationrequired

**Comment by Roman-Tarasiuk** [comment]
All other programs that enable proxy configuration (e.g. git, vscode, NuGet, my own downloader) work correctly through our company proxy.

**Comment by Roman-Tarasiuk** [comment]
In my own downloader (.NET, C#):
using (WebClient wc = new WebClient())
{
    WebProxy p = new WebProxy(proxy, true);
    p.Credentials = new NetworkCredential(login, password);
    WebRequest.DefaultWebProxy = p;
    wc.Proxy = p;
    // Downloading files.
}
In the code, proxy = "http://proxy:port".

**Comment by Roman-Tarasiuk** [comment]
Maybe, we talk about different versions of libman?
I have installed it using command:
**dotnet tool install --global Microsoft.Web.LibraryManager.Cli**

**Comment by Roman-Tarasiuk** [comment]
@jimmylewis Hi!
I have a workaround for the problem:
I cloned the solution and changed the private constructor of the WebRequestHandler class (src\LibraryManager\CacheService\WebRequestHandler.cs):
<pre>
private WebRequestHandler()
{
    HttpClientHandler httpMessageHandler = new HttpClientHandler();
    httpMessageHandler.Proxy = new WebProxy("http://proxy:port", true);
    httpMessageHandler.Proxy.Credentials = new NetworkCredential("domain\username", "password");
    httpMessageHandler.UseProxy = true;

    _httpClient = new HttpClient(httpMessageHandler);
}
</pre>
(I also added using System.Net; at the beginning).
I built the solution using the command:
**dotnet build**
After that in my own project's folder I run the commands:
**dotnet "C:\Users\username\SourcePath\LibraryManager\src\libman\bin\Debug\netcoreapp2.1\libman.dll" init**
**dotnet "C:\Users\username\SourcePath\LibraryManager\src\libman\bin\Debug\netcoreapp2.1\libman.dll" install jquery**
or any other external library – twitter-bootstrap, react etc.
And it works just fine. :)
Also interesting fact is that after that I run this command, I also can run the:
**libman install jquery**
(where libman.exe is installed by running the command from the my previous comment) and it also works pretty good, so I make conclusion that it creates and uses some local cache.


So you can add some command line option or config file that will contain this settings for proxy to resolve the issue.

**Comment by wshuman3** [comment]
How about submitting a pull request?

**Comment by jimmylewis** [comment]
(replying here instead of on linked PR, since this is where the larger discussion is happening)

@Roman-Tarasiuk I assume your proxy uses NTLM authentication?  My PR fix worked for me when I had a proxy using Basic authentication, once I had put the credentials into another app (e.g. the browser), which caused the creds to be stored in the Windows Credential Manager.  I tested it by clearing the LibMan cache (i.e. force it to download files again), building without my PR change, install a package, and verifying that it failed (HTTP 407 - proxy authentication failed), then build with my change, install a package, and it worked.  Changed the proxy password, repeat, same results (once I updated the stored credentials).

I don't have a setup for a proxy with NTLM or a different auth mechanism, so I'm not sure how to test there or how the behavior would be different.  Basic auth seemed to reuse the stored settings in the Credential Manager, but NTLM might be different.  Would love suggestions for how to improve the PR.

Things I'm trying to avoid:
1. Hard-coding credentials.  Obviously, this won't work from user to user.
2. Saving credentials to disk.  This is obviously an important security risk.  I can look into this more if we can't figure something else out, but I'd prefer to avoid it; the threat model and mitigations would likely get pretty messy.  It might be possible to use the Credential Manager here too, but there isn't a native .NET API for it, and it is platform specific, and it would require managing prompts whenever credentials change.
3. Having proxy settings be all-or-nothing.  I could easily imagine a scenario where someone is behind a proxy at work, but takes their laptop out and no longer needs the proxy configuration.  In this case, there should be an easy way to toggle back and forth, instead of having to manually configure LibMan each time.  My PR attempts to use the system settings, so that LibMan isn't managing the proxy settings on its own.  Again, alternative suggestions welcomed; the .NET APIs around proxy configuration seem to be pretty opaque about how to use them properly.

**Comment by jimmylewis** [comment]
A new version of the CLI package has been published to support this scenario (2.0.48).  It introduces a new `libman config` command which can be used for proxy settings:
`libman config --set http_proxy=http://example` will set a proxy server.

For users who need to specify credentials, we currently have a Windows-only solution.  If we get feedback to support this on other platforms we can look into options.  Credentials should be specified as:
`libman config --set http_proxy.user=myusername --setEncrypted http_proxy.password=passwordPlaintext`

To disable the proxy, you can set it to empty: `libman config --set http_proxy=`

Lastly, if you have URLs that bypass the proxy, you can use a semicolon delmited list with:
`libman config --set http_proxy.bypass=http://foo;http://bar`

**Comment by Roman-Tarasiuk** [comment]
@jimmylewis, it works pretty good! Thanks a lot!
:)

**Comment by okosodovictor** [comment]
Almost all my js library are failing to restore when i run restore client side library for my libman file. I am recieving this error " library could not be resolved by the "cdnjs" provider"
example: 
    {
      "library": "twitter-bootstrap@3.3.6",
      "destination": "wwwroot/lib/twitter-bootstrap/"
    },
    {
      "library": "font-awesome@4.1.0",
      "destination": "wwwroot/lib/font-awesome/"
    },
    {
      "library": "toastr.js@2.1.4",
      "destination": "wwwroot/lib/toastr.js/"
    },
None coud able to restore. I am using visual studio 2019.

**Comment by will056** [comment]
I faced the same problem. Libraries are not loaded:  "font-awesome@5.10.2", "bootstrap-datepicker@1.9.0", "tempusdominus-bootstrap-4@5.1.2", "bootstrap-select@1.13.11","bootstrap-fileinput@5.0.6"

**Comment by jimmylewis** [comment]
@will056 can you verify that it's an issue with the LibMan tool, and that the provider's CDN is working correctly?  As someone pointed out in a separate issue (but commenting about the same problem), Cdnjs had [an outage](https://status.cdnjs.com/incidents/0gdmkm4tl98d) earlier.  We can't do anything to improve beyond their reliability. 🤔

If it is a problem with LibMan and not the underlying CDN, please open a new issue.  This problem seems unrelated to this current issue.

**Comment by okosodovictor** [comment]
The issue was with the provider not with Libman tool. CDN had issues yesterday. 
https://status.cdnjs.com/incidents/0gdmkm4tl98d. Now all is working fine again.

**Comment by alexaka1** [comment]
I'm having an issue, where I physically cannot change the proxy config value. I run an administrator command prompt, run `libman config --set http_proxy=` and nothing happens. The proxy value is set by default to a proxy server of my workplace, but that's not the correct one that developers use, and I can't change it. Setting the user and password values work, but actually changing the proxy address does not.
