### ISSUE TITLE
[loc][Query][LibraryManager] Localizability of string:  0; "LIBMAN/RESOURCES/TEXT.RESX.InstallCommandProviderSpecificLogic"

### ISSUE THREAD

**Issue by PDostalek** [aspnet/LibraryManager#468]
Hi,
please help localization team to answer question from translator.

In case translator is not sure about context/meaning/localizability of string we raise a question to Core team.

Could you help please? Thanks!**

Source:
 CDNJS libraries have a library ID format of “<it id="1" pos="open">&lt;libraryName&gt;</it>@<it id="2" pos="open">&lt;libraryVersion&gt;</it>”\r\n For CDNJS libraries, if no version is specified in the library ID, the highest version available is used.

File Name:
libman\MultilingualResources\libman.xlf

Resource IDs of affected strings:

0; "LIBMAN/RESOURCES/TEXT.RESX.InstallCommandProviderSpecificLogic"
0; "LIBMAN/RESOURCES/TEXT.RESX.UnInstallCommandProviderSpecificLogic"
0; "(...) allPackage|ButtonText"
0; "MICROSOFT.WEB.LIBRARYMANAGER.VSIX/RESOURCES/TEXT.RESX.SelectLibraryToSelectFilesToInstall"
0; "MICROSOFT.WEB.LIBRARYMANAGER.VSIX/RESOURCES/TEXT.RESX.TypeToSearch"

Query:
Some elements, such as "libraryName", "libraryVersion" and "Type to search" seem localizable. Do we need to localize them?

**Comment by jimmylewis** [comment]
Hi @PDostalek,

Yes, these terms should be localized.  

The `libraryName` and `libraryVersion` strings are placeholders to indicate the syntax (a user might use the form `jquery@1.2.3` instead of how we show `<libraryName>@<libraryVersion>`)

"Type to search" is a directive.  The word "type" is refers to typing, not to a type of thing that is being searched for.

Does this answer the translator's questions?

**Comment by PDostalek** [comment]
Thanks , it should be enough to know.
