### ISSUE TITLE
The popper.js library could not be resolved

### ISSUE THREAD

**Issue by vitaaaly** [aspnet/LibraryManager#590]
### Functional impact
I can't restore popper.js today.

### Minimal repro steps

I try to restore libraries with this config:

```json
{
  "version": "1.0",
  "defaultProvider": "cdnjs",
  "libraries": [
    {
      "library": "popper.js@1.14.7",
      "destination": "wwwroot/lib/popper"
    }
  ]
}
```

### Actual result
libman.json : error LIB002: The "popper.js@1.14.7" library could not be resolved by the "cdnjs" provider

### Further technical details
Also I try to use unpkg and another version of popper.js, but I have the same error.

Microsoft Visual Studio Enterprise 2019
Version 16.6.2

**Comment by maxd** [comment]
I have a lot of similar errors during last month too i.e.:

```
libman.json : error LIB002: The "bootstrap-datepicker@1.9.0" library could not be resolved by the "cdnjs" provider
```

The two big problems here:

1. libman don't write detail information about such error even when verbose logs is enabled. So, there are no standard ways to investigate the reason of this problem on our side.
2. Looks like libman doesn't make several retries to download libraries because when I make several tries I can download all libraries without such errors.

**Comment by vitaaaly** [comment]
I tried again - library restored!

But @maxd comments seem reasonable.

**Comment by jimmylewis** [comment]
Closing as a duplicate.
