### ISSUE TITLE
Fails to download .DS_Store for CoreUI from unpkg.com

### ISSUE THREAD

**Issue by munkii** [aspnet/LibraryManager#613]
### Describe the bug
I am using the "Add Client-Side Library" option in Visual Studio 2019. I have sucessfully added Bootstrap and am now tryiong to add CoreUI. However CoreUi will not add successfuly. It fails right at the end trying to download .DS_Store

### To Reproduce
1. Using this version of Visual Studio 2019
2. Add Client-Side library
4. Choose "unpkg" as the Provider. (I cannot see coreui available from the others)
5. See the progress in Library Manger window as it downloads each file
6. Gets to the end and says 

Downloading file https://unpkg.com/@coreui/coreui@3.4.0/package.json... (MyProject)
**Failed to download resource from "https://unpkg.com/@coreui/coreui-pro@3.4.0/scss/.DS_Store"
Failed to download resource from "https://unpkg.com/@coreui/coreui@3.4.0/scss/.DS_Store"**

### Expected behavior
"coreui" folder appears in wwwroot/lib

### Additional context

VS2019 16.8.2
MS Library Manager 2.1.113+g422d40002e.RR

**Comment by jimmylewis** [comment]
This is a case of bad behavior coming from the Unpkg provider.  The metadata tells us that these files should exist, but then the download fails; we treat it as an irrecoverable error because we can't tell .DS_Store from alert.css in terms of importance.

One workaround here would be to use a glob pattern to filter out the files you don't want.  For example:
```
  "libraries": [
    {
      "provider": "unpkg",
      "library": "@coreui/coreui@3.4.0",
      "destination": "wwwroot/js/coreui/coreui/",
      "files": [ 
        "**/*",
        "!**/.DS_Store" 
      ]
    }
```

Alternatively, I tried switching to the jsdelivr provider, and that served up the .ds_store files without issue (it looks like unpkg refuses to serve those files at all).

**Comment by munkii** [comment]
Thanks. I thought I tried all the other providers looking for CoreUI and couldn't see but as you say it is available on "jsdelivr"
