### ISSUE TITLE
Libman CLI does not properly support local dotnet tool installation

### ISSUE THREAD

**Issue by JHorvath-MaxetaTech** [aspnet/LibraryManager#624]
### Describe the bug
Installing the Libman CLI as a local (NOT GLOBAL) dotnet tool, with a custom nuget.config associated with the solution, does not create/update the toolResolverCache file with the proper local PathToExecutable.

### To Reproduce
1. Using .NET 5.0 (with nuget.exe available)
2. Unzip the attached [Libman.Issue.zip](https://github.com/aspnet/LibraryManager/files/6070067/Libman.Issue.zip)
3. Navigate to the .ini folder
4. Run the Libman.Issue.bat to scaffold out the solution (or open it and run all the commands manually)
5. See error: "Could not execute because the specified command or file was not found."

### Expected behavior
While libman is allowed to be installed as a dotnet tool locally (and restores to the custom nuget package folder for the local solution), it presently does not operate as expected. The local path is not being used to lookup an run the libman.dll. When no prior global installation had been performed this is a hard failure, when the tool was previously globally installed, the wrong version of libman could potentially be run unbeknownst to the user,

### Additional context
It seems that "dotnet tool install/restore/update" does not update the toolResolverCache file for libman to point to the proper path.

Presently the toolResolverCache file:
  %userprofile%\.dotnet\toolResolverCache\1\microsoft.web.librarymanager.cli

only contains a PathToExecutable equal to the pre-determined global location under the user profile: 
  %userprofile%\\.nuget\\packages\\microsoft.web.librarymanager.cli\\2.1.113\\tools/netcoreapp2.1/any/libman.dll

when it should be getting updated to the local location associated with the solution's custom nuget.config:
  ..\\lib\\nuget\\microsoft.web.librarymanager.cli\\2.1.113\\tools\\netcoreapp2.1\\any\\libman.dll

It seems important for this to local/standalone libman scenario to be allowed (for use in a continuous integration environments). Several different solutions, expecting different versions of the libman CLI should be allowed to function independently and not unexpectedly all be working off a singular global install.

**Comment by jimmylewis** [comment]
I don't think the `dotnet tool` invocation will update the toolResolverCache, but it will set it correctly if it's not yet present.  Here's what I tried:
1. Removed the LibMan CLI package from my global package cache (%userprofile%\.nuget\packages)
2. Removed the existing toolResolverCache file.
3. Ran your script from the .zip file

Now I see that I have the package installed to the expected path under the project directory (in my case, d:\temp\repro\src\lib\nuget\microsoft.web.librarymanager.cli\2.1.113)
And  the toolResolverCache seems to be pointing to it: 
```
[{"Version":"2.1.113","TargetFramework":"net5.0","RuntimeIdentifier":"any","Name":"libman","Runner":"dotnet","PathToExecutable":"d:\\temp\\repro\\src\\lib\\nuget\\microsoft.web.librarymanager.cli\\2.1.113\\tools/netcoreapp2.1/any/libman.dll"}]
```

My guess is if you're seeing the `%userprofile%\.nuget\packages` path, it's probably because it was installed there previously and they didn't update the toolResolverCache. If I try to install this tool in another project under an entirely different path (`dotnet new tool-manifest ; dotnet tool install Microsoft.Web.LibraryManager.Cli ; dotnet tool restore`) I still see the toolResolverCache pointing to the same path from before.

My guess would be that once the dotnet tool resolver has cached a local tool, it reuses that cached location for any other local tool installs.  In other words, it doesn't well adapt to the globalPackagesFolder changing from one repo (where you set it in your original steps) to another (where it should maybe use a different globalPackagesFolder).  Unfortunately, there isn't much that LibMan can do about this, it's all behavior handled by the dotnet SDK.

Another approach that might achieve the tool isolation you want is to install the tool using `dotnet tool install Microsoft.Web.LibraryManager.Cli --tool-path ./some/local/path`.  This would let you then invoke it based on that path (`./some/local/path/libman.exe`) in a way that is guaranteed to not be impacted by other repos or tool installations.
