### ISSUE TITLE
nuget Microsoft.Web.LibraryManager.Build skips restoring in depend project if target = publish

### ISSUE THREAD

**Issue by leotsarev** [aspnet/LibraryManager#643]
### Describe the bug
I have projects A and B.
Dependencies:
A → B → Microsoft.Web.LibraryManager.Build 
A → Microsoft.Web.LibraryManager.Build 

B.csproj skips restoring if I use dotnet publish A

### To Reproduce
1. dotnet CLI 6.0.100
2. dotnet publish A -o out
3. A is restored, but not B

### Expected behavior
B is always restored

### Note
1. dotnet CLI 6.0.100
2. dotnet build A
2. dotnet publish A -o out
3. Everything fine

### Additional context
I have to remove libman.json from publishing or I'll have error about publishing files with same name.

A project: https://github.com/joinrpg/joinrpg-net/blob/03df0502ce42d0f9a3614995f59385583b508b42/src/JoinRpg.Portal/JoinRpg.Portal.csproj
B project: https://github.com/joinrpg/joinrpg-net/blob/03df0502ce42d0f9a3614995f59385583b508b42/src/JoinRpg.WebComponents/JoinRpg.WebComponents.csproj

**Comment by jimmylewis** [comment]
I cloned your repo but it looks like this is working fine for me.  

When I do `dotnet publish src\JoinRpg.Portal -o out` from a clean state (just ran git clean to be sure), I see that the LibraryManagerRestore target runs in both projects.  From the log for JoinRpg.WebComponents.csproj:

> Restore operation started...
> Restoring library bootstrap-select@1.13.9...
> wwwroot/lib/bootstrap-select/css/bootstrap-select.css written to destination
> wwwroot/lib/bootstrap-select/css/bootstrap-select.css.map written to destination
> etc...
> 1 libraries restored in 0.99 seconds

When I do it again (incremental build), I see both targets run again, but since the files are in place, there's no copying done.  The target still sets the FilesForPackagingFromProject items whether clean or incremental.

> Restore operation started...
> Restoring library bootstrap-select@1.13.9...
> 1 libraries restored in 0.56 seconds

Can you provide a binlog (add the `-bl` parameter to your build steps) that shows the target not running?
