### ISSUE TITLE
Support updating packages in the LibraryManagerRestore msbuild task.

### ISSUE THREAD

**Issue by jakenuts** [aspnet/LibraryManager#669]
I'd like to include a script in a common package used by several web applications. I was able to accomplish this with libman and a razor class library but to improve upon that I was hoping that when the package was built it would update the library to it's latest published version. I could add this by installing/calling the global tool "libman update @sentry/browser" prior to building, but it would seem like a good fit for the LibraryManagerRestore build task. Is that possible?

Thanks!

**Comment by jimmylewis** [comment]
Using the build task, I think it would work if you installed using the `latest` version, e.g. `@sentry/browser@latest` in the libman.json file.  Each time you build, it should check for the latest version of the library and install it.

Obviously, this makes your build indeterministic since the result will depend on the state of the world at the time you build.
