### ISSUE TITLE
The resource is not embedded in the assembly

### ISSUE THREAD

**Issue by Varorbc** [aspnet/LibraryManager#670]
### Is your feature request related to a problem? Please describe.
I wanted the restored file to be embedded in the assembly when it was built, but it wasn't

### Additional context
```
  <ItemGroup>
    <EmbeddedResource Include="wwwroot\**\*" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Web.LibraryManager.Build" Version="2.1.161" TreatAsUsed="true" />
  </ItemGroup>
```

**Comment by jimmylewis** [comment]
Hi @Varorbc, I just want to confirm that I understand your scenario.  You have the two snippets defined in your project file, and the files specified in your libman.json file are not being included in your assembly as embedded references?

I believe this is due to the [evaluation order](https://docs.microsoft.com/en-us/visualstudio/msbuild/comparing-properties-and-items?view=vs-2022#property-and-item-evaluation-order) in MSBuild - the `<ItemGroup>` is evaluated before targets are executed, so the blob pattern expands to nothing.

To make this work you would need a target to contain the `<ItemGroup>` so that it would be evaluated after the LibMan restore completed.  For example, something like this (not sure if this works exactly right, I'm writing it without testing):

```
<Target Name="EvaluateItemsAfterLibmanRestore" AfterTargets="LibraryManagerRestore">
  <!-- putting this in a target ensures it is evaluated after the LibMan restore has completed and the files exist on disk -->
  <ItemGroup>
    <EmbeddedResource Include="wwwroot\**\*" />
  </ItemGroup>
</Target>
```

**Comment by Varorbc** [comment]
@jimmylewis  thank you very much
