### ISSUE TITLE
Visual Studio for Mac Support?

### ISSUE THREAD

**Issue by mrlife** [aspnet/LibraryManager#69]
Is this feature going to be available in Visual Studio for Mac?

**Comment by mrward** [comment]
The LibMan extension is also supposed to be available from the Extensions Manager in Visual Studio for Mac but there are problems with the server since it does not seem to publish the extension for later versions sometimes. You have to publish it manually again for later versions of the IDE so it is visible. Currently it does not seem to be listed for VS Mac 8.3 - I will republish it.

**Comment by ppdac** [comment]
All good. Thank you!
<img width="598" alt="image" src="https://user-images.githubusercontent.com/3385925/67632730-cc146580-f87d-11e9-9a6c-328efd56bdfe.png">

**Comment by jimmylewis** [comment]
Closing this issue in deferral to #561.  The Readme has been updated with the instructions to install for VS for Mac.
