### ISSUE TITLE
Package Microsoft.Web.LibraryManager.Cli 2.1.175 is not compatible with net6.0

### ISSUE THREAD

**Issue by LLIAMAH** [aspnet/LibraryManager#700]
### Describe the bug
Severity	Code	Description	Project	File	Line	Suppression State

- Error		Package 'Microsoft.Web.LibraryManager.Cli 2.1.175' has a package type 'DotnetTool' that is not supported by project 'WebComments'.				
- Error	NU1202	Package Microsoft.Web.LibraryManager.Cli 2.1.175 is not compatible with net6.0 (.NETCoreApp,Version=v6.0). Package Microsoft.Web.LibraryManager.Cli 2.1.175 supports: netcoreapp2.1 (.NETCoreApp,Version=v2.1) / any	WebComments	C:\Users\User\source\repos\WebComments\WebComments\WebComments.csproj	1	
- Error	NU1212	Invalid project-package combination for Microsoft.Web.LibraryManager.Cli 2.1.175. DotnetToolReference project style can only contain references of the DotnetTool type 	WebComments	C:\Users\User\source\repos\WebComments\WebComments\WebComments.csproj	1	

### To Reproduce
1. Microsoft Visual Studio Community 2022 (64-bit) - Current Version 17.3.4
2. Create Asp.NET Core (MVC) project
3. NuGet Packages - try to add: Microsoft.Web.LibraryManager.Build 2.1.175 - successful
4. NuGet Packages - try to add: Microsoft.Web.LibraryManager.Cli 2.1.175 - **FAILED**

### Expected behavior
Possibility to add Microsoft.Web.LibraryManager.Cli 2.1.175 via NuGet

### Screenshots
![image](https://user-images.githubusercontent.com/4736499/190231945-b59f6acc-fd29-4325-84fb-192df33b0246.png)

### Additional context
Found this during search of workaround for this [more important problem](https://github.com/aspnet/LibraryManager/issues/699)

**Comment by jimmylewis** [comment]
The Microsoft.Web.LibraryManager.Cli is a CLI tool to be installed using `dotnet tool install`, not to be added as a PackageReference.  This is expected behavior as the error messages indicate, though it may be an issue that the NuGet wizard is showing this package (it should realize that it's incompatible).

While the LibraryManager.Cli tool is built against netcore2.1, it installs and runs fine on systems with only newer versions of the dotnet sdk installed.
