### ISSUE TITLE
LibraryManager is missing at vs 2017 15.7 preview 5

### ISSUE THREAD

**Issue by lettucebo** [aspnet/LibraryManager#74]
After upgrade to vs 2017 15.7 preview 5

LibraryManager is gone, can't find it anywhere

I try reopen VS, reboot computer and repair VS 2017 17.5 preview 5 to factory reset, but nothing works

![image](https://user-images.githubusercontent.com/891383/39418022-7e5a947c-4c8a-11e8-9da5-dc8de79684a8.png)

![image](https://user-images.githubusercontent.com/891383/39418118-0d6889da-4c8b-11e8-9435-68783c729d42.png)

**Comment by DerAlbertCom** [comment]
Is this permanent removed for 15.7 or a bug?

**Comment by lettucebo** [comment]
Actually I don't know, I don't have another machine can cleanly install fresh VS preview

I have report this issue at developer community 

https://developercommunity.visualstudio.com/content/problem/241526/library-manager-is-missing.html

**Comment by engryEngineer** [comment]
We are experiencing this on 2 machines with fresh installs of preview 5 (we do not have any instances of preview 5 that has libman).

**Comment by justcla** [comment]
Library Manager is still in preview mode. It was available in the 15.7 previews, but we removed it from the 15.7 official release. It is included in the first 15.8 preview, which will be available very soon.

In the meantime, if you'd like to continue using LibMan, you can manually create and install the latest LibMan extension.
To install the latest LibMan extension:
- Clone the source from the [Library Manager GitHub repo](https://github.com/aspnet/LibraryManager/).
- Build the solution in Visual Studio 2017.
- Install the VSIX: "Microsoft.Web.LibraryManager.vsix" found in the directory: [YourSolutionFolder]\src\LibraryManager.Vsix\bin\Release

Thank you, all, for your continued interest in LibMan.

**Comment by StevenLiekens** [comment]
@justcla I'm confused, what are we supposed to use in VS2017 update 7?

If I understand the documentation then libman replaced bower tooling. If I understand your comment then libman was pulled from VS because it wasn't ready. So is there no built-in package manager for client-side library right now? Jeez...

**Comment by lettucebo** [comment]
@StevenLiekens I think the best way is download the project and compile the vsix by self

**Comment by StevenLiekens** [comment]
That's if you insist on using LibMan but it sounds like it's not ready for production so what do we use until then?

**Comment by StevenLiekens** [comment]
@hajekj thanks for sharing, nice blog article too

**Comment by KenSpr** [comment]
Same for us: there are no menu options for managing client-side libraries (VS 15.7.4;  .Net Core 2.1 SDK). 

In the last year and 3 months of working with .Net Core (versions 1.0  --> 2.1) the options to manage client side have changed several times. As I recall, beta's used Npm then 1.0 used Nuget w/o Bower. Later versions promoted Bower followed by LibMan and now it missing completely! What is up?

**Comment by KenSpr** [comment]
Also, note that 'VS2017 15.8 Preview 2's implementation of Libman lacks any UI (.Net Core 2.1 SDK/Web App). The Bower implementation worked like Nuget offering both a search tool for locating libraries and a tool for comparing installed versions with the later version-options.

**Comment by smolander** [comment]
I tried building it from the repo but got the following error message: 

"The current .NET SDK does not support targeting .NET Core 2.1.  Either target .NET Core 2.0 or lower, or use a version of the .NET SDK that supports .NET Core 2.1."

Has anyone had a similar problem? (I also tried the pre-built version, and it did not work...)

**Comment by augustobotossi** [comment]
I compiled the spice after cloning the repo, but after running the VSIX file, I get the error message "A value for 'Component' needs to be specified in the catalog."

**Comment by jefftucker** [comment]
I've experienced the errors both @smolander and @augustobotossi have reported.  I get the error message "A value for 'Component' needs to be specified in the catalog." even installing the VSIX file from a CI build (I used this one: https://ci.appveyor.com/project/aspnetci/librarymanager/build/1.0.949/artifacts).  I have not been able to build the project locally either due to a variety of errors although I think I was able to eventually get the .NET Core 2.1 issue to go away but there were multiple issues building the test project that look like missing references or packages.  

I can provide logs or whatever of any of this if it would be helpful.

**Comment by kevlyons** [comment]
I also compiled from source and got the same error as @augustobotossi!

**Comment by lettucebo** [comment]
If you encounter "A value for 'Component' needs to be specified in the catalog." issue
Please reference issue #302 
I have file a issue and got resolve

**Comment by FredyWenger** [comment]
Unbelievable...
I have created a project a while ago with a preview of .net core and VS2015.
Installed VS2017 **15.7.5 (release!)**
The old project (without any touch) don't compile anymore in VS2015 after install of VS2017...
In VS 2017 15.7.5 **release**, all tools (Bower and NPM) are **completely missing!**
Libman **cannot** be installed with  **15.7.5 (release!)**
Searching and think about what to do since more than a full day now (and... according to all postings, I'm not the only one).
**Thanks MS to give your customers something to do by every update to VS and/or .net Core!**

**Comment by StevenLiekens** [comment]
@FredyWenger 15.7.5 is outdated at this point, update to 15.9 and it should have libman preinstalled

**Comment by FredyWenger** [comment]
@StevenLiekens:
I know, that libman ist preinstalled in 15.9, but I don't want to update to 15.9 yet, as we have a lot of SW (including e.g. Xamarin app's) in use at our customers and tested all the SW with 15.7.5 a while  ago.
So.. I fear negative siede effects (especially regarding the Xamarin integration) , if we update.
I really don't understand, that MS removes tools (that their customers need to work) without any replacement and forces all to do update the whole VS as it is not possible to install such a "small tool" in an official release of VS....

**Comment by StevenLiekens** [comment]
Agree they shouldn't have removed bower/npm before libman was ready... strange move
